"""The controller (M5): what the daemon does each cycle, so autolab runs with nobody at the keyboard.

    uv run autolab start | stop [--cancel-running] | resume | status

Each cycle, after the cascade has advanced (autolab.evaluate.advance_all), `step()`:

1. Enabled? `autolab stop` sets it off (state in autolab/state/controller.json); in-flight
   programs still finish unless --cancel-running.
2. Paused? A Claude usage limit (HTTP 429) pauses proposing until the reset time in the
   message (or an hour, if it can't be parsed). Repeated early rejections pause too:
   `max_consecutive_early_rejects` programs in a row rejected at static/cpu/params means the
   prompt or code is broken, and more calls would only burn budget.
3. Data policy. If the incumbent's full-budget runs read `data_limited` with confidence >=
   data_trigger_confidence and no bigger dataset has been tried for this incumbent: build one
   (data_growth x the current docs; a doc-prefix slice if a bigger set already exists), upload
   it, and start a data check (autolab.evaluate.start_data_check). If the check says it helped,
   run the incumbent's screens on the new data and start a new session there (noise from the
   check's 3 full seeds + those screens). Otherwise the "didn't help" note stays in the
   notebook as capacity evidence, and the policy re-arms when a new incumbent is accepted (so
   does the compute ladder). Builds and uploads run as detached subprocesses so the daemon
   keeps cycling.
4. Proposals: keep up to max_in_flight unfinished programs, each new one only if the
   rolling-24h spend (Modal actual + committed estimates of pending calls + Claude) plus
   the expected cost of one candidate stays within daily_usd, and total Modal spend stays
   within [modal] max_usd.
5. Record: every event goes to autolab/notebook.jsonl, and autolab/NOTEBOOK.md is
   regenerated. Each newly accepted program is committed to the local branch
   `autolab-accepted` (worktree ../wiki-llm-autolab-wt/accepted), so the daemon never touches
   the working tree of the `autolab` branch.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import tomllib
from datetime import datetime, timedelta, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

from autolab import evaluate as ev
from autolab.config import REPO_ROOT

STATE = REPO_ROOT / "autolab" / "state"
CONTROL = STATE / "controller.json"
NOTEBOOK = REPO_ROOT / "autolab" / "notebook.jsonl"
NOTEBOOK_MD = REPO_ROOT / "autolab" / "NOTEBOOK.md"
ACCEPTED_WT = REPO_ROOT.parent / "wiki-llm-autolab-wt" / "accepted"
ACCEPTED_BRANCH = "autolab-accepted"
RUNS = REPO_ROOT / "autolab" / "runs"
EARLY = {"static", "cpu", "params"}


def now() -> datetime:
    return datetime.now(timezone.utc)


def iso(t: datetime) -> str:
    return t.isoformat(timespec="seconds")


def controller_cfg() -> dict:
    return tomllib.loads((REPO_ROOT / "autolab" / "config.toml").read_text()).get("controller", {})


def daily_budget(ctl: dict, ccfg: dict, t: datetime | None = None) -> float:
    """[controller] daily_usd, unless a one-time override (autolab budget --daily X --hours H) is active."""
    ov = ctl.get("daily_usd_override") or {}
    try:
        if ov and datetime.fromisoformat(ov["until"]) > (t or now()):
            return float(ov["usd"])
    except (KeyError, ValueError):
        pass
    return float(ccfg.get("daily_usd", 10.0))


def load_control(path: Path | None = None) -> dict:
    path = path or CONTROL  # resolved at call time (tests redirect CONTROL)
    try:
        return json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return {"enabled": False}


def save_control(ctl: dict, path: Path | None = None) -> None:
    path = path or CONTROL
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(ctl, indent=2))
    tmp.replace(path)


# --- notebook -----------------------------------------------------------------------------------


def note(event: str, notebook: Path | None = None, **fields) -> dict:
    notebook = notebook or NOTEBOOK
    entry = {"at": iso(now()), "event": event, **fields}
    notebook.parent.mkdir(parents=True, exist_ok=True)
    with open(notebook, "a") as fh:
        fh.write(json.dumps(entry) + "\n")
    return entry


def read_notebook(notebook: Path | None = None) -> list[dict]:
    notebook = notebook or NOTEBOOK
    try:
        return [json.loads(line) for line in notebook.read_text().splitlines() if line.strip()]
    except (OSError, json.JSONDecodeError):
        return []


def render_notebook_md(entries: list[dict], session: dict | None, progs: dict, out: Path | None = None) -> None:
    out = out or NOTEBOOK_MD
    lines = ["# Autolab notebook", "", "Regenerated by the daemon from `autolab/notebook.jsonl`. Newest first.", ""]
    if session:
        inc = progs.get(session["incumbent"])
        lines += [f"**Session** `{session.get('name')}` · incumbent **{session['incumbent']}**"
                  + (f" (full val {inc.scores.get('full_mean'):.4f} over {inc.scores.get('n_seeds')} seeds)" if inc else "")
                  + f" · seed noise σ {session['noise']['full']['std']:.4f}", ""]
        lines += ["| program | parent | by | outcome | full val (n) | rationale |", "| --- | --- | --- | --- | --- | --- |"]
        for p in sorted(progs.values(), key=lambda q: int(q.id[1:]), reverse=True)[:40]:
            fm, n = p.scores.get("full_mean"), p.scores.get("n_seeds")
            full = f"{fm:.4f} ({n})" if fm is not None else "–"
            where = f" @{p.stage}" if p.status == "rejected" else ""
            why = p.rationale[:140].replace("|", "/")
            lines.append(f"| {p.id} | {p.parent_id or '–'} | {p.created_by} | {p.status}{where} | {full} | {why} |")
        lines.append("")
    lines += ["## Events", ""]
    for e in reversed(entries[-300:]):
        rest = {k: v for k, v in e.items() if k not in ("at", "event")}
        lines.append(f"- `{e['at']}` **{e['event']}** " + "; ".join(f"{k}: {v}" for k, v in rest.items())[:500])
    out.write_text("\n".join(lines) + "\n")


# --- spend --------------------------------------------------------------------------------------


def spend_24h(calls: dict, llm_spend: list[dict], t: datetime) -> dict:
    since = t - timedelta(hours=24)

    def recent(ts: str | None) -> bool:
        try:
            return ts is not None and datetime.fromisoformat(ts.replace("Z", "+00:00")) >= since
        except ValueError:
            return False

    modal_done = sum(c.get("usd") or 0 for c in calls.values() if c["state"] != "pending" and recent(c.get("submitted_at")))
    modal_pending = sum(c.get("usd_estimate") or 0 for c in calls.values() if c["state"] == "pending")
    llm = sum(e.get("usd") or 0 for e in llm_spend if recent(e.get("at")))
    return {"modal_done": modal_done, "modal_pending": modal_pending, "llm": llm,
            "total": modal_done + modal_pending + llm}


def frees_at(calls: dict, llm_spend: list[dict], t: datetime, target: float) -> str | None:
    """When enough finished spend ages out of the 24-hour window for the total to drop to `target`."""
    items = []
    for c in calls.values():
        if c["state"] != "pending" and c.get("submitted_at"):
            items.append((datetime.fromisoformat(c["submitted_at"]), c.get("usd") or 0.0))
    for e in llm_spend:
        if e.get("at"):
            items.append((datetime.fromisoformat(e["at"]), e.get("usd") or 0.0))
    total = spend_24h(calls, llm_spend, t)["total"]
    for at, usd in sorted(i for i in items if i[0] >= t - timedelta(hours=24)):
        if total <= target:
            break
        total -= usd
        if total <= target:
            return iso(at + timedelta(hours=24))
    return None if total > target else iso(t)


def expected_candidate_usd(session: dict, gpu_usd_per_s: float, cfg: dict) -> float:
    """Screen always; full run about half the time; plus a proposer call."""
    caps = session["wall_caps"]
    return (caps["screen"] + cfg.get("p_full", 0.5) * caps["full"] + 180 * (1 + cfg.get("p_full", 0.5))) \
        * gpu_usd_per_s + cfg.get("llm_usd_per_call", 0.15)


# --- rate limits ----------------------------------------------------------------------------------


RESET = re.compile(r"resets\s+(\w{3})\s+(\d{1,2})\s+at\s+(\d{1,2})(?::(\d{2}))?\s*(am|pm)\s*\(([^)]+)\)", re.I)


def parse_reset(message: str, t: datetime) -> datetime:
    """"...resets Sep 30 at 6pm (America/Chicago)" -> that instant (UTC); else one hour from t."""
    m = RESET.search(message or "")
    if not m:
        return t + timedelta(hours=1)
    mon, day, hour, minute, ampm, tz = m.groups()
    hour = int(hour) % 12 + (12 if ampm.lower() == "pm" else 0)
    try:
        zone = ZoneInfo(tz)
        local = datetime.strptime(f"{mon} {day} {t.astimezone(zone).year}", "%b %d %Y").replace(
            hour=hour, minute=int(minute or 0), tzinfo=zone)
    except Exception:  # noqa: BLE001 - unknown zone/format: be conservative
        return t + timedelta(hours=1)
    if local < t:
        local = local.replace(year=local.year + 1)
    return local.astimezone(timezone.utc) + timedelta(minutes=5)


# --- accepted programs → git ------------------------------------------------------------------------


def commit_accepted(p, session: dict, repo: Path | None = None, worktree: Path | None = None, log=print) -> str | None:
    """Write the accepted program's model.py/train.py into the `autolab-accepted` worktree and commit."""
    repo, worktree = repo or REPO_ROOT, worktree or ACCEPTED_WT
    from autolab.program import base_sources, render

    def git(*a, cwd=repo, check=True):
        return subprocess.run(["git", *a], cwd=cwd, capture_output=True, text=True, check=check)

    if not worktree.exists():
        worktree.parent.mkdir(parents=True, exist_ok=True)
        exists = git("rev-parse", "--verify", ACCEPTED_BRANCH, check=False).returncode == 0
        git("worktree", "add", *( [str(worktree), ACCEPTED_BRANCH] if exists else
                                  ["-b", ACCEPTED_BRANCH, str(worktree), session["base_commit"]]))
    files = render(base_sources(repo, p.base_commit), p.blocks)
    for rel in ("mini_llm/model.py", "mini_llm/train.py"):
        (worktree / "src" / rel).write_text(files[rel])
    (worktree / "autolab" / "accepted").mkdir(parents=True, exist_ok=True)
    (worktree / "autolab" / "accepted" / f"{session.get('name')}-{p.id}.json").write_text(
        json.dumps({"program": p.id, "session": session.get("name"), "hparams": p.hparams, "scores": p.scores,
                    "rationale": p.rationale, "parent": p.parent_id, "created_by": p.created_by}, indent=2))
    git("add", "-A", cwd=worktree)
    msg = (f"autolab: accept {session.get('name')}/{p.id} (full val {p.scores['full_mean']:.4f} over "
           f"{p.scores.get('n_seeds')} seeds)\n\nHypothesis: {p.rationale}\n\nResult: {p.reason}\n"
           f"Hyperparameters: {json.dumps(p.hparams)}\nParent: {p.parent_id}; proposed by {p.created_by}.\n\n"
           f"Co-Authored-By: Claude <noreply@anthropic.com>")
    r = git("commit", "-m", msg, cwd=worktree, check=False)
    if r.returncode != 0:
        log(f"commit of {p.id} failed: {(r.stderr or r.stdout)[-300:]}")
        return None
    sha = git("rev-parse", "--short", "HEAD", cwd=worktree).stdout.strip()
    log(f"{p.id} committed to {ACCEPTED_BRANCH} as {sha}")
    if controller_cfg().get("push_accepted", False):  # owner allows pushing this branch (never forced)
        r = git("push", "origin", ACCEPTED_BRANCH, cwd=worktree, check=False)
        log(f"pushed {ACCEPTED_BRANCH}" if r.returncode == 0 else f"push of {ACCEPTED_BRANCH} failed: {r.stderr[-300:]}")
    return sha


# --- the data policy ----------------------------------------------------------------------------------


def incumbent_diagnosis(session: dict, progs: dict, runs_dir: Path) -> dict | None:
    inc = progs[session["incumbent"]]
    best = None
    for rid in inc.runs.get("full", []) + inc.runs.get("confirm", []):
        try:
            d = json.loads((runs_dir / rid / "diagnosis.json").read_text())
        except (OSError, json.JSONDecodeError):
            continue
        lab = next((x for x in d["labels"] if x["name"] == "data_limited"), None)
        if lab and (best is None or lab["confidence"] > best["confidence"]):
            best = lab
    return best


def _spawn(args: list[str], log_name: str) -> int:
    logf = open(STATE / log_name, "a")
    proc = subprocess.Popen([sys.executable, "-m", "autolab.cli", *args], cwd=REPO_ROOT, stdout=logf,
                            stderr=subprocess.STDOUT, start_new_session=True)
    return proc.pid


def _alive(pid: int | None) -> bool:
    if not pid:
        return False
    try:
        os.kill(pid, 0)
    except OSError:
        return False
    try:  # reap if it's our finished child
        return os.waitpid(pid, os.WNOHANG) == (0, 0)
    except ChildProcessError:
        return True


def rearm(flow: dict, session: dict, what: str) -> bool:
    """A finished policy flow (not_helped / failed) was about one incumbent; a new one gets its own check.
    Reset the flow to idle when the incumbent has changed since."""
    if flow.get("state") not in ("not_helped", "failed") or flow.get("program") in (None, session["incumbent"]):
        return False
    note(f"{what}_rearmed", session=session.get("name"), program=session["incumbent"], previous=flow.get("program"),
         previous_state=flow.get("state"))
    flow.clear()
    flow.update(session=session.get("name"), state="idle")
    return True


def data_step(ctl: dict, session: dict, progs: dict, calls: dict, cfg: dict, paths: ev.Paths, log) -> None:
    from autolab.config import load_config

    flow = ctl.setdefault("data_flow", {})
    sname = session.get("name")
    if flow.get("session") != sname:
        flow.clear()
        flow.update(session=sname, state="idle")
    rearm(flow, session, "data_policy")
    datasets_dir = load_config().datasets_dir
    runs_dir = RUNS

    if flow["state"] in ("idle", "uploading", "checking") and not budget_ok(flow, session, calls, cfg):
        return  # the data check trains 3 full seeds; wait for the rolling-24h budget like proposals do
    if flow["state"] == "idle":
        lab = incumbent_diagnosis(session, progs, runs_dir)
        if not lab or lab["confidence"] < cfg.get("data_trigger_confidence", 0.75):
            return
        if any(c.get("program") == session["incumbent"] and c.get("kind", "data") == "data"
               for c in session.get("data_checks", [])):
            return
        cur = session.get("dataset_id") or ev.evolve_cfg()["dataset_id"]
        cur_docs = json.loads((datasets_dir / cur / "dataset.json").read_text())["docs"] \
            if (datasets_dir / cur / "dataset.json").exists() else int(re.sub(r"\D", "", cur)) * 1000
        want = int(cur_docs * cfg.get("data_growth", 2))
        from autolab.datasets import dataset_id

        target = dataset_id(want)
        flow.update(target=target, trigger=lab, started=iso(now()), program=session["incumbent"])
        note("data_limited", session=sname, program=session["incumbent"], confidence=lab["confidence"],
             evidence=lab["evidence"], plan=f"build {target} ({want:,} docs) and test the incumbent on it")
        if (datasets_dir / target / "train.pt").exists():
            flow["state"] = "built"
        else:
            bigger = sorted((d for d in datasets_dir.iterdir() if (d / "dataset.json").exists()
                             and json.loads((d / "dataset.json").read_text())["docs"] > want), key=lambda d: d.name)
            args = (["data", "slice", bigger[0].name, "--docs", str(want)] if bigger
                    else ["data", "build", "--num-examples", str(want)])
            flow.update(state="building", pid=_spawn(args, "data_build.log"), cmd=" ".join(args))
            from autolab.activity import set_activity

            set_activity("data", f"data policy: {' '.join(args)}")
            log(f"data: {' '.join(args)} (pid {flow['pid']})")
    elif flow["state"] == "building":
        if _alive(flow.get("pid")):
            return
        if (datasets_dir / flow["target"] / "dataset.json").exists():
            flow["state"] = "built"
        else:
            flow["state"] = "failed"
            note("data_build_failed", session=sname, target=flow["target"], log="autolab/state/data_build.log")
    if flow["state"] == "built":
        flow.update(state="uploading", pid=_spawn(["modal", "upload-data"], "data_upload.log"))
    elif flow["state"] == "uploading":
        if _alive(flow.get("pid")):
            return
        chk = ev.start_data_check(session["incumbent"], flow["target"], paths=paths)
        flow.update(state="checking", check=chk["id"])
        note("data_check_started", session=sname, dataset=flow["target"], program=session["incumbent"], runs=chk["runs"])
    elif flow["state"] == "checking":
        chk = next((c for c in ev.load_session(paths).get("data_checks", []) if c["id"] == flow["check"]), None)
        if not chk or chk["status"] == "running":
            return
        note("data_check_done", session=sname, dataset=flow["target"], verdict=chk.get("verdict"),
             helped=chk.get("helped"), losses=chk.get("losses"))
        if not chk.get("helped"):
            flow["state"] = "not_helped"
            return
        submit_screens(flow, session, progs, paths, log)
    elif flow["state"] == "baselining":
        if any(calls.get(r, {}).get("state", "pending") == "pending" for r in flow["screen_runs"]):
            return
        new = switch_session(flow, session, progs, paths, log)
        flow["state"] = "switched"
        flow["new_session"] = new


def budget_ok(flow: dict, session: dict, calls: dict, cfg: dict) -> bool:
    """Room in the rolling-24h budget for what the next data step will submit."""
    from autolab import modal_backend as mb

    if flow["state"] not in ("idle", "uploading"):
        return True  # nothing new gets submitted before the verdict
    llm = []
    try:
        llm = [json.loads(x) for x in (STATE / "llm_spend.jsonl").read_text().splitlines() if x.strip()]
    except OSError:
        pass
    cost = 3 * (session["wall_caps"]["full"] + 180) * mb.price_per_s(ev.evolve_cfg()["gpu"])
    ok = spend_24h(calls, llm, now())["total"] + cost <= daily_budget(load_control(), cfg)
    flow["waiting_for_budget"] = not ok
    return ok


def submit_screens(flow: dict, session: dict, progs: dict, paths: ev.Paths, log, submit=None) -> None:
    from autolab.config import load_config
    from autolab.program import base_sources, materialize, render

    if submit is None:
        from autolab.modal_backend import submit as modal_submit

        def submit(req, gpu, src):
            return modal_submit(req, gpu, src_root=src)

    cfg = ev.evolve_cfg()
    p = progs[session["incumbent"]]
    src = materialize(render(base_sources(REPO_ROOT, p.base_commit), p.blocks), paths.work(f"data-screen-{p.id}"))
    ids = []
    for seed in (1, 2, 3):
        req = ev._request(p, "screen", seed, cfg, session)
        dataset = flow.get("dataset", flow["target"])
        req.run_id = f"ev-{session.get('name')}-{flow.get('kind', 'data')}-{flow['target']}-{p.id}-screen-s{seed}"
        req.dataset_id = dataset
        req.train_tokens = str(load_config().datasets_dir / dataset / "train.pt")
        submit(req, cfg["gpu"], src)
        ids.append(req.run_id)
    flow.update(state="baselining", screen_runs=ids)
    log(f"{flow.get('kind', 'data')}: {flow['target']} helped; baselining screens {ids}")


def switch_session(flow: dict, session: dict, progs: dict, paths: ev.Paths, log) -> str:
    """Start a new session on the bigger data with the incumbent as its p0."""
    chk = next(c for c in session["data_checks"] if c["id"] == flow["check"])
    inc = progs[session["incumbent"]]
    name = f"{session.get('name', 's').split('-')[0]}+{flow['target']}"
    new_paths = ev.Paths(ev.STATE_ROOT / name)
    ev.init_session(session["base_commit"], inc.hparams, {"screen": flow["screen_runs"], "full": chk["runs"]},
                    paths=new_paths, budgets=session["budgets"], name=name, blocks=inc.blocks,
                    dataset_id=flow["target"], rationale=f"{inc.id} of {session.get('name')} moved to {flow['target']}",
                    origin={"session": session.get("name"), "program": inc.id, "via": "data",
                            "detail": f"{session.get('dataset_id')} → {flow['target']} (data policy)"})
    ev.set_active_session(name)
    note("session_switched", old=session.get("name"), new=name, dataset=flow["target"], verdict=chk["verdict"])
    log(f"switched to session {name} on {flow['target']}")
    return name


def port_from_old_sessions(ctl: dict, session: dict, log) -> list[str]:
    """Programs accepted in other sessions (e.g. after a data switch) get re-evaluated here, once."""
    ported = ctl.setdefault("ported", [])
    out = []
    for paths in ev.all_session_paths():
        other = ev.load_session(paths)
        if not other or other.get("name") == session.get("name") or other.get("ablation"):
            continue  # an ablation arm's programs never enter the main search
        for p in ev.programs(paths).values():
            key = f"{other.get('name')}/{p.id}"
            if p.parent_id is None or p.status != "accepted" or key in ported:
                continue
            child = ev.port(p, other.get("name"))
            ported.append(key)
            note("ported", session=session.get("name"), program=child.id, source=key,
                 full_mean_there=p.scores.get("full_mean"))
            log(f"ported {key} -> {session.get('name')}/{child.id}")
            out.append(child.id)
    return out


def retest_step(ctl: dict, session: dict, log, root: Path | None = None) -> list[str]:
    """Once per regime change (a session with an origin), queue targeted retests of near misses from earlier
    regimes: [evolve.memory] retest_per_regime of them, each re-applied to the new champion by a directed
    child. Near misses are the results most likely to flip with more data or compute, and waiting for the
    proposer to rediscover a specific one is unreliable. Other rejections simply expire (autolab.memory)."""
    from autolab import memory

    st = ctl.setdefault("retest", {})
    sessions, done, pending = (st.setdefault(k, []) for k in ("sessions", "done", "pending"))
    name = session.get("name")
    if not (session.get("origin") or {}).get("session") or name in sessions:
        return []
    sessions.append(name)
    picks = [m.key for m in memory.retest_candidates(session, ev.evolve_cfg(), root or ev.STATE_ROOT, set(done))]
    done.extend(picks)
    pending.extend(picks)
    note("retest_queued", session=name, programs=picks)
    if picks:
        log(f"retest: near misses from earlier regimes queued for {name}: {', '.join(picks)}")
    return picks


# --- the no-evolution ablation (autolab.ablation) -------------------------------------------------------


def affordable(session: dict, t: datetime, ctl: dict, ccfg: dict) -> bool:
    """Room for one more candidate of `session` in the rolling-24h budget and under the Modal cap."""
    from autolab import modal_backend as mb

    calls = mb.load_calls()
    need = expected_candidate_usd(session, mb.price_per_s(ev.evolve_cfg()["gpu"]), ccfg)
    modal_total = sum(c.get("usd") or c.get("usd_estimate") or 0 for c in calls.values())
    return (spend_24h(calls, _llm_spend(), t)["total"] + need <= daily_budget(ctl, ccfg, t)
            and modal_total + need <= mb.max_usd())


def ablation_step(ctl: dict, ccfg: dict, t: datetime, log) -> int:
    """Propose for running no-evolution arms (at most ablation_max_in_flight unfinished each, within budget),
    and note each arm's comparison once all its candidates have finished. Returns the number proposed."""
    from autolab import ablation

    made = 0
    for apaths in ablation.active_arms():
        asess, progs = ev.load_session(apaths), ev.programs(apaths)
        in_flight = sum(p.status not in ev.DONE for p in progs.values() if p.parent_id)
        left = asess["ablation"]["target"] - len(ablation.candidates(progs))
        while in_flight < ccfg.get("ablation_max_in_flight", 2) and left > 0 and affordable(asess, t, ctl, ccfg):
            child = _generate(log, paths=apaths)
            note("proposed", session=asess["name"], program=child.id, parent=child.parent_id, arm=ablation.ARM,
                 created_by=child.created_by, rationale=child.rationale[:400], status=child.status,
                 fallback=child.meta.get("fallback_reason"), cost_usd=child.meta.get("cost_usd"))
            made += 1
            left -= 1
            in_flight += child.status not in ev.DONE
    for apaths in ev.all_session_paths():
        asess = ev.load_session(apaths)
        if not ablation.is_ablation(asess) or asess["ablation"].get("finished"):
            continue
        cands = ablation.candidates(ev.programs(apaths))
        if len(cands) >= asess["ablation"]["target"] and all(p.status in ev.DONE for p in cands):
            cmp = ablation.compare(asess["name"], apaths.root.parent)
            asess["ablation"]["finished"] = iso(t)
            ev.save_session(asess, apaths)
            note("ablation_finished", session=asess["name"], source=cmp["source"], compared_at=cmp["compared_at"],
                 arms=cmp["arms"], summary=ablation.render(cmp))
            log(ablation.render(cmp))
    return made


# --- the compute ladder -----------------------------------------------------------------------------


def stalled_children(session: dict, progs: dict) -> int:
    """Finished children since the incumbent was set that didn't beat it (the search has stalled)."""
    since = (session.get("incumbent_history") or [{}])[-1].get("at", "")
    return sum(1 for p in progs.values() if p.parent_id and p.status in ev.DONE and p.status != "accepted"
               and p.created_at >= since)


def ladder_step(ctl: dict, session: dict, progs: dict, calls: dict, cfg: dict, paths: ev.Paths, log) -> None:
    """Raise the token budget when searching at this one has stalled and training longer clearly pays.

    idle -> (stalled >= ladder_patience, next budget <= max_full_tokens, data policy quiet, budget ok)
    checking (incumbent at factor x tokens, 3 seeds) -> not_helped | baselining (3 screens) -> switched
    (new session "<name>@<N>M" with that budget; the data policy re-arms there).
    """
    if not cfg.get("ladder", True):
        return
    flow = ctl.setdefault("ladder", {})
    sname = session.get("name")
    if flow.get("session") != sname:
        flow.clear()
        flow.update(session=sname, state="idle")
    rearm(flow, session, "ladder")
    cur = session["budgets"]["full_tokens"]
    step_tokens = ev.evolve_cfg()["block_size"] * progs[session["incumbent"]].hparams["batch_size"]
    nxt = int(round(cur * cfg.get("ladder_factor", 1.5) / step_tokens)) * step_tokens
    if flow["state"] == "idle":
        data_busy = ctl.get("data_flow", {}).get("state") not in (None, "idle", "not_helped", "failed")
        stalled = stalled_children(session, progs)
        if (data_busy or nxt > cfg.get("max_full_tokens", cur) or stalled < cfg.get("ladder_patience", 4)
                or any(c.get("kind") == "budget" and c["program"] == session["incumbent"]
                       for c in session.get("data_checks", []))):
            flow["waiting"] = {"stalled": stalled, "next_tokens": nxt, "data_busy": data_busy}
            return
        from autolab.modal_backend import price_per_s

        cost = 3 * (session["wall_caps"]["full"] * nxt / cur + 180) * price_per_s(ev.evolve_cfg()["gpu"])
        if spend_24h(calls, _llm_spend(), now())["total"] + cost > daily_budget(ctl, cfg):
            flow["waiting"] = {"budget": f"needs ~${cost:.2f}"}
            return
        dataset = session.get("dataset_id") or ev.evolve_cfg()["dataset_id"]
        chk = ev.start_data_check(session["incumbent"], dataset, paths=paths, tokens=nxt)
        flow.update(state="checking", check=chk["id"], kind="budget", target=f"{nxt // 1_000_000}M", dataset=dataset,
                    tokens=nxt, started=iso(now()), program=session["incumbent"])
        flow.pop("waiting", None)
        note("ladder_check_started", session=sname, program=session["incumbent"], tokens=nxt, stalled=stalled,
             runs=chk["runs"])
        log(f"ladder: {stalled} children stalled; testing {session['incumbent']} at {nxt:,} tokens")
    elif flow["state"] == "checking":
        chk = next((c for c in ev.load_session(paths).get("data_checks", []) if c["id"] == flow["check"]), None)
        if not chk or chk["status"] == "running":
            return
        note("ladder_check_done", session=sname, tokens=flow["tokens"], verdict=chk.get("verdict"),
             helped=chk.get("helped"), losses=chk.get("losses"))
        if not chk.get("helped"):
            flow["state"] = "not_helped"
            return
        submit_screens(flow, session, progs, paths, log)
    elif flow["state"] == "baselining":
        if any(calls.get(r, {}).get("state", "pending") == "pending" for r in flow["screen_runs"]):
            return
        chk = next(c for c in session["data_checks"] if c["id"] == flow["check"])
        inc = progs[session["incumbent"]]
        name = f"{sname.split('@')[0]}@{flow['target']}"
        ev.init_session(session["base_commit"], inc.hparams, {"screen": flow["screen_runs"], "full": chk["runs"]},
                        paths=ev.Paths(ev.STATE_ROOT / name),
                        budgets={**session["budgets"], "full_tokens": flow["tokens"]}, name=name, blocks=inc.blocks,
                        dataset_id=flow["dataset"],
                        rationale=f"{inc.id} of {sname} at {flow['tokens']:,} tokens (compute ladder)",
                        origin={"session": sname, "program": inc.id, "via": "ladder",
                                "detail": f"{session['budgets']['full_tokens'] / 1e6:.0f}M → {flow['tokens'] / 1e6:.1f}M tokens (compute ladder)"})
        ev.set_active_session(name)
        note("session_switched", old=sname, new=name, tokens=flow["tokens"], verdict=chk["verdict"])
        log(f"ladder: switched to session {name}")
        flow.update(state="switched", new_session=name)


# --- M8: measure the incumbent's four dimensions; note frontier changes ----------------------------------


def measure_step(ctl: dict, session: dict, progs: dict, calls: dict, ccfg: dict, t: datetime, paths, log) -> None:
    """The quality champion needs quality/context/train/inference metrics to anchor the frontier; programs
    accepted before the eval suite existed get one measured run (budget-gated like everything else)."""
    inc = progs[session["incumbent"]]
    if (inc.scores.get("metrics") or {}).get("long_range_score") is not None:
        return
    if inc.id in (session.get("measures") or {}):
        return
    from autolab.modal_backend import price_per_s

    cost = (session["wall_caps"]["full"] / max(ev.evolve_cfg()["wall_cap_mult"], 1) * 1.1 + 300) * price_per_s(ev.evolve_cfg()["gpu"])
    if spend_24h(calls, _llm_spend(), t)["total"] + cost > daily_budget(ctl, ccfg, t):
        ctl["measure_waiting"] = f"budget: measuring {inc.id} needs ~${cost:.2f}"
        return
    ctl.pop("measure_waiting", None)
    rid = ev.start_measure(inc.id, paths=paths)
    note("measure_started", session=session.get("name"), program=inc.id, run=rid)
    log(f"measuring {inc.id}'s four dimensions ({rid})")


def note_frontier(ctl: dict, log) -> None:
    from autolab.pareto import frontier

    seen = ctl.setdefault("frontier", {})
    for paths in ev.all_session_paths():
        sess = ev.load_session(paths)
        if not sess:
            continue
        front = frontier(list(ev.programs(paths).values()), ev.sigma(sess))
        ids = sorted(p.id for p in front)
        old = set(seen.get(sess.get("name"), []))
        for p in front:
            if p.id not in old:
                m = p.scores.get("metrics", {})
                note("frontier_joined", session=sess.get("name"), program=p.id, full_mean=p.scores.get("full_mean"),
                     long_range_score=m.get("long_range_score"), context=m.get("context"),
                     train_min=round((m.get("train_wall_s") or 0) / 60, 1),
                     decode_ms_per_token=m.get("decode_ms_per_token"))
                log(f"{sess.get('name')}/{p.id} joined the Pareto frontier")
        for pid in old - set(ids):
            note("frontier_left", session=sess.get("name"), program=pid)
        seen[sess.get("name")] = ids


# --- research (M7) ------------------------------------------------------------------------------------


def research_step(ctl: dict, session: dict, progs: dict, calls: dict, ccfg: dict, t: datetime, log) -> None:
    """Audit the winner when it changes (or the search stalls); then one directed child per new card."""
    from autolab import research

    rcfg = research.research_cfg()
    if not rcfg.get("enabled", False):
        return
    st = ctl.setdefault("research", {})
    if st.get("state") == "running":
        if _alive(st.get("pid")):
            return
        result = STATE / "research_result.json"
        try:
            out = json.loads(result.read_text())
            result.unlink()
        except (OSError, json.JSONDecodeError):
            out = {"error": "research run produced no result (see autolab/state/research.log)"}
        st.update(state="idle", last_finished=iso(t), last_result=out)
        st.setdefault("pending_directed", []).extend(out.get("added", []))
        note("research_done", session=session.get("name"), program=st.get("program"), added=out.get("added"),
             cost_usd=out.get("cost_usd"), summary=(out.get("summary") or out.get("error") or "")[:500])
        return
    # when to research: new winner not audited yet, a long stall, or nothing yet this session
    key = f"{session.get('name')}/{session['incumbent']}"
    stalled = stalled_children(session, progs)
    trigger = None
    if key not in st.get("audited", []):
        trigger = (f"{session['incumbent']} is the current best (just accepted or never audited): check it for "
                   "outdated or missing techniques before we build on it.")
    elif stalled >= rcfg.get("stall_patience", 6) and st.get("stall_mark") != f"{key}@{stalled // rcfg.get('stall_patience', 6)}":
        trigger = (f"The search has stalled: {stalled} children since {session['incumbent']} was accepted, none better. "
                   "Look for techniques we haven't tried.")
        st["stall_mark"] = f"{key}@{stalled // rcfg.get('stall_patience', 6)}"
    if trigger is None:
        return
    share = float(rcfg.get("budget_share", 0.3)) * daily_budget(ctl, ccfg, t)
    spent = sum(e.get("usd") or 0 for e in _llm_spend() if str(e.get("tag", "")).startswith("research")
                and e.get("at") and datetime.fromisoformat(e["at"]) >= t - timedelta(hours=24))
    if spent + rcfg.get("est_usd_per_run", 1.5) > share:
        st["waiting"] = f"research budget: ${spent:.2f} used of ${share:.2f} (30% of the daily budget)"
        return
    total = spend_24h(calls, _llm_spend(), t)["total"]
    if total + rcfg.get("est_usd_per_run", 1.5) > daily_budget(ctl, ccfg, t):
        st["waiting"] = "daily budget"
        return
    st.pop("waiting", None)
    st.setdefault("audited", []).append(key)
    st.update(state="running", program=session["incumbent"], trigger=trigger, started=iso(t),
              pid=_spawn(["research", "run", "--trigger", trigger, "--result", str(STATE / "research_result.json")],
                         "research.log"))
    note("research_started", session=session.get("name"), program=session["incumbent"], trigger=trigger)
    log(f"research: auditing {session['incumbent']} ({trigger[:80]})")


def _llm_spend() -> list[dict]:
    try:
        return [json.loads(x) for x in (STATE / "llm_spend.jsonl").read_text().splitlines() if x.strip()]
    except OSError:
        return []


# --- one controller step ------------------------------------------------------------------------------


def step(log=print, generate=None, t: datetime | None = None) -> dict:
    """Run once per daemon cycle. Returns a small status dict for the heartbeat."""
    from autolab import modal_backend as mb
    from autolab.llm import RateLimited

    t = t or now()
    ctl = load_control()
    status = {"enabled": ctl.get("enabled", False)}
    session_paths = ev.Paths()
    session = ev.load_session(session_paths)
    if session is None:
        return {**status, "note": "no session"}
    progs = ev.programs(session_paths)
    ccfg = controller_cfg()

    # record newly finished programs (and commit acceptances) in every session, whether or not
    # proposing is enabled: an older session can still finish programs after a data switch
    from autolab.program import save

    for spaths in ev.all_session_paths():
        sess = ev.load_session(spaths)
        if not sess:
            continue
        name = sess.get("name")
        sprogs = ev.programs(spaths)
        if ev.update_noise_pool(sess, sprogs):  # re-estimate seed noise from every multi-seed program
            ev.save_session(sess, spaths)
            std, df = ev.pooled_full_std(sess)
            note("noise_updated", session=name, pooled_std=round(std, 5), df=df,
                 base_std=round(sess["noise"]["full"]["std"], 5), sigma=round(ev.sigma(sess), 5))
        seen = set(ctl.setdefault("recorded", {}).get(name, []))
        for p in sprogs.values():
            if p.parent_id is None or p.id in seen or p.status not in ev.DONE:
                continue
            note("program_done", session=name, program=p.id, status=p.status, stage=p.stage,
                 reason=p.reason[:300], full_mean=p.scores.get("full_mean"), n_seeds=p.scores.get("n_seeds"),
                 created_by=p.created_by)
            if p.status == "accepted" and ccfg.get("commit_accepted", True) and not sess.get("ablation"):
                p.meta["commit"] = commit_accepted(p, sess, log=log)
                save(p, spaths.programs)
            seen.add(p.id)
        ctl["recorded"][name] = sorted(seen)
    progs = ev.programs(session_paths)
    try:
        note_frontier(ctl, log)
    except Exception as exc:  # noqa: BLE001
        log(f"frontier error: {type(exc).__name__}: {exc}")

    if not ctl.get("enabled"):
        save_control(ctl)
        return status

    calls = mb.load_calls()
    try:  # the data policy spends money too, so it only runs while enabled
        data_step(ctl, session, progs, calls, ccfg, session_paths, log)
    except Exception as exc:  # noqa: BLE001 - never let the data policy take the loop down
        log(f"data policy error: {type(exc).__name__}: {exc}")
        ctl.setdefault("data_flow", {})["error"] = str(exc)[:500]
    if ctl.get("data_flow", {}).get("state") == "switched":  # new session: reload
        session_paths = ev.Paths()
        session, progs = ev.load_session(session_paths), ev.programs(ev.Paths())
    try:
        ladder_step(ctl, session, progs, calls, ccfg, session_paths, log)
    except Exception as exc:  # noqa: BLE001
        log(f"ladder error: {type(exc).__name__}: {exc}")
        ctl.setdefault("ladder", {})["error"] = str(exc)[:500]
    if ctl.get("ladder", {}).get("state") == "switched":
        session_paths = ev.Paths()
        session, progs = ev.load_session(session_paths), ev.programs(ev.Paths())
    port_from_old_sessions(ctl, session, log)
    try:
        retest_step(ctl, session, log)
    except Exception as exc:  # noqa: BLE001
        log(f"retest error: {type(exc).__name__}: {exc}")
    status["data"] = {k: v for k, v in ctl.get("data_flow", {}).items() if k in ("state", "target", "check", "new_session")}
    status["ladder"] = {k: v for k, v in ctl.get("ladder", {}).items() if k in ("state", "target", "waiting", "new_session")}
    paused = ctl.get("paused_until")
    if paused and datetime.fromisoformat(paused) > t:
        save_control(ctl)
        return {**status, "paused_until": paused, "pause_reason": ctl.get("pause_reason"),
                "blocked": {"kind": "paused", "until": paused, "reason": ctl.get("pause_reason")}}

    alert = STATE / "infra_alert.json"
    if alert.exists():  # the cascade found the protected test suite broken on the incumbent itself
        info = json.loads(alert.read_text())
        ctl.update(paused_until=iso(t + timedelta(hours=24)), pause_reason=f"infrastructure: {info['reason'][:200]}")
        note("paused", reason=ctl["pause_reason"], until=ctl["paused_until"])
        alert.unlink()
        save_control(ctl)
        return {**status, "paused_until": ctl["paused_until"]}

    children = [p for p in progs.values() if p.parent_id is not None]
    recent = sorted(children, key=lambda p: int(p.id[1:]))[-ccfg.get("max_consecutive_early_rejects", 4):]
    if (len(recent) == ccfg.get("max_consecutive_early_rejects", 4)
            and all(p.status == "rejected" and p.stage in EARLY for p in recent)
            and ctl.get("early_reject_ack") != recent[-1].id):
        ctl.update(paused_until=iso(t + timedelta(hours=6)), early_reject_ack=recent[-1].id,
                   pause_reason=f"{len(recent)} proposals in a row rejected before training ({recent[-1].reason[:160]})")
        note("paused", reason=ctl["pause_reason"], until=ctl["paused_until"])
        save_control(ctl)
        return {**status, "paused_until": ctl["paused_until"]}

    in_flight = sum(p.status not in ev.DONE for p in children)
    if len(children) >= ccfg.get("max_programs_per_session", 200):
        save_control(ctl)
        return {**status, "note": "max_programs_per_session reached"}
    llm_spend = []
    try:
        llm_spend = [json.loads(x) for x in (STATE / "llm_spend.jsonl").read_text().splitlines() if x.strip()]
    except OSError:
        pass
    try:
        measure_step(ctl, session, progs, mb.load_calls(), ccfg, t, session_paths, log)
    except Exception as exc:  # noqa: BLE001
        log(f"measure error: {type(exc).__name__}: {exc}")
    try:
        research_step(ctl, session, progs, mb.load_calls(), ccfg, t, log)
    except Exception as exc:  # noqa: BLE001
        log(f"research error: {type(exc).__name__}: {exc}")
        ctl.setdefault("research", {}).update(state="idle", error=str(exc)[:500])
    status["research"] = {k: v for k, v in ctl.get("research", {}).items() if k in ("state", "program", "waiting", "pending_directed")}
    price = mb.price_per_s(ev.evolve_cfg()["gpu"])
    made = 0
    try:
        made += ablation_step(ctl, ccfg, t, log)
    except RateLimited as exc:
        until = parse_reset(str(exc), t)
        ctl.update(paused_until=iso(until), pause_reason=f"Claude usage limit: {str(exc)[:200]}")
        note("paused", reason=ctl["pause_reason"], until=ctl["paused_until"])
        save_control(ctl)
        return {**status, "paused_until": ctl["paused_until"]}
    except Exception as exc:  # noqa: BLE001
        log(f"ablation error: {type(exc).__name__}: {exc}")
    while in_flight < ccfg.get("max_in_flight", 4):
        sp = spend_24h(mb.load_calls(), llm_spend, t)
        need = expected_candidate_usd(session, price, ccfg)
        modal_total = sum(c.get("usd") or c.get("usd_estimate") or 0 for c in mb.load_calls().values())
        daily = daily_budget(ctl, ccfg, t)
        if sp["total"] + need > daily:
            status["budget"] = f"24h spend ${sp['total']:.2f} + next ~${need:.2f} > ${daily}"
            status["blocked"] = {"kind": "daily", "spend_24h": round(sp["total"], 2), "need": round(need, 2),
                                 "limit": daily, "unblock_at_limit": round(sp["total"] + need + 0.01, 2),
                                 "frees_at": frees_at(mb.load_calls(), llm_spend, t, daily - need)}
            break
        if modal_total + need > mb.max_usd():
            status["budget"] = f"Modal total ${modal_total:.2f} + ~${need:.2f} > cap ${mb.max_usd()}"
            status["blocked"] = {"kind": "modal_cap", "modal_total": round(modal_total, 2), "need": round(need, 2),
                                 "limit": mb.max_usd(), "unblock_at_limit": round(modal_total + need + 0.01, 2)}
            break
        pending = ctl.get("research", {}).get("pending_directed") or []
        retests = ctl.get("retest", {}).get("pending") or []
        card = retest = None
        if pending:  # test each new research card right away, as a directed child of the incumbent
            from autolab import research

            card = next((c for c in research.load_cards() if c["id"] == pending[0]), None)
        elif retests:  # then near misses from earlier regimes, re-applied to the incumbent
            retest = retests[0]
        try:
            directed = card is not None or retest is not None
            child = _generate(log, card=card, retest=retest) if directed else (generate or _generate)(log)
            if pending:
                pending.pop(0)
            elif retests:
                retests.pop(0)
        except RateLimited as exc:
            until = parse_reset(str(exc), t)
            ctl.update(paused_until=iso(until), pause_reason=f"Claude usage limit: {str(exc)[:200]}")
            note("paused", reason=ctl["pause_reason"], until=ctl["paused_until"])
            break
        note("proposed", session=session.get("name"), program=child.id, parent=child.parent_id,
             created_by=child.created_by, rationale=child.rationale[:400], hparams_patch={
                 k: v for k, v in child.hparams.items() if progs.get(child.parent_id) and
                 progs[child.parent_id].hparams.get(k) != v},
             status=child.status, fallback=child.meta.get("fallback_reason"), cost_usd=child.meta.get("cost_usd"),
             retest_of=child.meta.get("retest_of"))
        made += 1
        in_flight += child.status not in ev.DONE
    save_control(ctl)
    render_notebook_md(read_notebook(), ev.load_session(ev.Paths()), ev.programs(ev.Paths()))
    return {**status, "proposed": made, "in_flight": in_flight}


def _generate(log, card: dict | None = None, retest: str | None = None, paths: ev.Paths | None = None):
    from autolab.generate import generate_one

    return generate_one(log=log, card=card, retest=retest, paths=paths)
