"""The controller (M5): what the daemon does each cycle, so autolab runs with nobody at the keyboard.

    uv run autolab start | stop [--cancel-running] | resume | status

Each cycle, after the cascade has advanced (autolab.evaluate.advance_all), `step()`:

1. Enabled? `autolab stop` sets it off (state in autolab/state/controller.json); in-flight
   programs still finish unless --cancel-running.
2. Paused? A Claude usage limit (HTTP 429) pauses proposing until the reset time in the
   message (or an hour, if it can't be parsed). Repeated early rejections pause too:
   `max_consecutive_early_rejects` programs in a row rejected at static/cpu/params means the
   prompt or code is broken, and more calls would only burn budget.
3. Data policy. If the incumbent's full-budget runs read `data_limited` with confidence >=
   data_trigger_confidence and no bigger dataset has been tried in this session: build one
   (data_growth x the current docs; a doc-prefix slice if a bigger set already exists), upload
   it, and start a data check (autolab.evaluate.start_data_check). If the check says it helped,
   run the incumbent's screens on the new data and start a new session there (noise from the
   check's 3 full seeds + those screens). Otherwise the "didn't help" note stays in the
   notebook as capacity evidence. Builds and uploads run as detached subprocesses so the daemon
   keeps cycling.
4. Proposals: keep up to max_in_flight unfinished programs, each new one only if the
   rolling-24h spend (Modal actual + committed estimates of pending calls + Claude) plus
   the expected cost of one candidate stays within daily_usd, and total Modal spend stays
   within [modal] max_usd.
5. Record: every event goes to autolab/notebook.jsonl, and autolab/NOTEBOOK.md is
   regenerated. Each newly accepted program is committed to the local branch
   `autolab-accepted` (worktree ../wiki-llm-autolab-wt/accepted), so the daemon never touches
   the working tree of the `autolab` branch.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import tomllib
from datetime import datetime, timedelta, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

from autolab import evaluate as ev
from autolab.config import REPO_ROOT

STATE = REPO_ROOT / "autolab" / "state"
CONTROL = STATE / "controller.json"
NOTEBOOK = REPO_ROOT / "autolab" / "notebook.jsonl"
NOTEBOOK_MD = REPO_ROOT / "autolab" / "NOTEBOOK.md"
ACCEPTED_WT = REPO_ROOT.parent / "wiki-llm-autolab-wt" / "accepted"
ACCEPTED_BRANCH = "autolab-accepted"
RUNS = REPO_ROOT / "autolab" / "runs"
EARLY = {"static", "cpu", "params"}


def now() -> datetime:
    return datetime.now(timezone.utc)


def iso(t: datetime) -> str:
    return t.isoformat(timespec="seconds")


def controller_cfg() -> dict:
    return tomllib.loads((REPO_ROOT / "autolab" / "config.toml").read_text()).get("controller", {})


def daily_budget(ctl: dict, ccfg: dict, t: datetime | None = None) -> float:
    """[controller] daily_usd, unless a one-time override (autolab budget --daily X --hours H) is active."""
    ov = ctl.get("daily_usd_override") or {}
    try:
        if ov and datetime.fromisoformat(ov["until"]) > (t or now()):
            return float(ov["usd"])
    except (KeyError, ValueError):
        pass
    return float(ccfg.get("daily_usd", 10.0))


def load_control(path: Path | None = None) -> dict:
    path = path or CONTROL  # resolved at call time (tests redirect CONTROL)
    try:
        return json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return {"enabled": False}


def save_control(ctl: dict, path: Path | None = None) -> None:
    path = path or CONTROL
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(ctl, indent=2))
    tmp.replace(path)


# --- notebook -----------------------------------------------------------------------------------


def note(event: str, notebook: Path | None = None, **fields) -> dict:
    notebook = notebook or NOTEBOOK
    entry = {"at": iso(now()), "event": event, **fields}
    notebook.parent.mkdir(parents=True, exist_ok=True)
    with open(notebook, "a") as fh:
        fh.write(json.dumps(entry) + "\n")
    return entry


def read_notebook(notebook: Path | None = None) -> list[dict]:
    notebook = notebook or NOTEBOOK
    try:
        return [json.loads(line) for line in notebook.read_text().splitlines() if line.strip()]
    except (OSError, json.JSONDecodeError):
        return []


def render_notebook_md(entries: list[dict], session: dict | None, progs: dict, out: Path | None = None) -> None:
    out = out or NOTEBOOK_MD
    lines = ["# Autolab notebook", "", "Regenerated by the daemon from `autolab/notebook.jsonl`. Newest first.", ""]
    if session:
        inc = progs.get(session["incumbent"])
        lines += [f"**Session** `{session.get('name')}` · incumbent **{session['incumbent']}**"
                  + (f" (full val {inc.scores.get('full_mean'):.4f} over {inc.scores.get('n_seeds')} seeds)" if inc else "")
                  + f" · seed noise σ {session['noise']['full']['std']:.4f}", ""]
        lines += ["| program | parent | by | outcome | full val (n) | rationale |", "| --- | --- | --- | --- | --- | --- |"]
        for p in sorted(progs.values(), key=lambda q: int(q.id[1:]), reverse=True)[:40]:
            fm, n = p.scores.get("full_mean"), p.scores.get("n_seeds")
            full = f"{fm:.4f} ({n})" if fm is not None else "–"
            where = f" @{p.stage}" if p.status == "rejected" else ""
            why = p.rationale[:140].replace("|", "/")
            lines.append(f"| {p.id} | {p.parent_id or '–'} | {p.created_by} | {p.status}{where} | {full} | {why} |")
        lines.append("")
    lines += ["## Events", ""]
    for e in reversed(entries[-300:]):
        rest = {k: v for k, v in e.items() if k not in ("at", "event")}
        lines.append(f"- `{e['at']}` **{e['event']}** " + "; ".join(f"{k}: {v}" for k, v in rest.items())[:500])
    out.write_text("\n".join(lines) + "\n")


# --- spend --------------------------------------------------------------------------------------


def spend_24h(calls: dict, llm_spend: list[dict], t: datetime) -> dict:
    since = t - timedelta(hours=24)

    def recent(ts: str | None) -> bool:
        try:
            return ts is not None and datetime.fromisoformat(ts.replace("Z", "+00:00")) >= since
        except ValueError:
            return False

    modal_done = sum(c.get("usd") or 0 for c in calls.values() if c["state"] != "pending" and recent(c.get("submitted_at")))
    modal_pending = sum(c.get("usd_estimate") or 0 for c in calls.values() if c["state"] == "pending")
    llm = sum(e.get("usd") or 0 for e in llm_spend if recent(e.get("at")))
    return {"modal_done": modal_done, "modal_pending": modal_pending, "llm": llm,
            "total": modal_done + modal_pending + llm}


def expected_candidate_usd(session: dict, gpu_usd_per_s: float, cfg: dict) -> float:
    """Screen always; full run about half the time; plus a proposer call."""
    caps = session["wall_caps"]
    return (caps["screen"] + cfg.get("p_full", 0.5) * caps["full"] + 180 * (1 + cfg.get("p_full", 0.5))) \
        * gpu_usd_per_s + cfg.get("llm_usd_per_call", 0.15)


# --- rate limits ----------------------------------------------------------------------------------


RESET = re.compile(r"resets\s+(\w{3})\s+(\d{1,2})\s+at\s+(\d{1,2})(?::(\d{2}))?\s*(am|pm)\s*\(([^)]+)\)", re.I)


def parse_reset(message: str, t: datetime) -> datetime:
    """"...resets Sep 30 at 6pm (America/Chicago)" -> that instant (UTC); else one hour from t."""
    m = RESET.search(message or "")
    if not m:
        return t + timedelta(hours=1)
    mon, day, hour, minute, ampm, tz = m.groups()
    hour = int(hour) % 12 + (12 if ampm.lower() == "pm" else 0)
    try:
        zone = ZoneInfo(tz)
        local = datetime.strptime(f"{mon} {day} {t.astimezone(zone).year}", "%b %d %Y").replace(
            hour=hour, minute=int(minute or 0), tzinfo=zone)
    except Exception:  # noqa: BLE001 - unknown zone/format: be conservative
        return t + timedelta(hours=1)
    if local < t:
        local = local.replace(year=local.year + 1)
    return local.astimezone(timezone.utc) + timedelta(minutes=5)


# --- accepted programs → git ------------------------------------------------------------------------


def commit_accepted(p, session: dict, repo: Path | None = None, worktree: Path | None = None, log=print) -> str | None:
    """Write the accepted program's model.py/train.py into the `autolab-accepted` worktree and commit."""
    repo, worktree = repo or REPO_ROOT, worktree or ACCEPTED_WT
    from autolab.program import base_sources, render

    def git(*a, cwd=repo, check=True):
        return subprocess.run(["git", *a], cwd=cwd, capture_output=True, text=True, check=check)

    if not worktree.exists():
        worktree.parent.mkdir(parents=True, exist_ok=True)
        exists = git("rev-parse", "--verify", ACCEPTED_BRANCH, check=False).returncode == 0
        git("worktree", "add", *( [str(worktree), ACCEPTED_BRANCH] if exists else
                                  ["-b", ACCEPTED_BRANCH, str(worktree), session["base_commit"]]))
    files = render(base_sources(repo, p.base_commit), p.blocks)
    for rel in ("mini_llm/model.py", "mini_llm/train.py"):
        (worktree / "src" / rel).write_text(files[rel])
    (worktree / "autolab" / "accepted").mkdir(parents=True, exist_ok=True)
    (worktree / "autolab" / "accepted" / f"{session.get('name')}-{p.id}.json").write_text(
        json.dumps({"program": p.id, "session": session.get("name"), "hparams": p.hparams, "scores": p.scores,
                    "rationale": p.rationale, "parent": p.parent_id, "created_by": p.created_by}, indent=2))
    git("add", "-A", cwd=worktree)
    msg = (f"autolab: accept {session.get('name')}/{p.id} (full val {p.scores['full_mean']:.4f} over "
           f"{p.scores.get('n_seeds')} seeds)\n\nHypothesis: {p.rationale}\n\nResult: {p.reason}\n"
           f"Hyperparameters: {json.dumps(p.hparams)}\nParent: {p.parent_id}; proposed by {p.created_by}.\n\n"
           f"Co-Authored-By: Claude <noreply@anthropic.com>")
    r = git("commit", "-m", msg, cwd=worktree, check=False)
    if r.returncode != 0:
        log(f"commit of {p.id} failed: {(r.stderr or r.stdout)[-300:]}")
        return None
    sha = git("rev-parse", "--short", "HEAD", cwd=worktree).stdout.strip()
    log(f"{p.id} committed to {ACCEPTED_BRANCH} as {sha}")
    return sha


# --- the data policy ----------------------------------------------------------------------------------


def incumbent_diagnosis(session: dict, progs: dict, runs_dir: Path) -> dict | None:
    inc = progs[session["incumbent"]]
    best = None
    for rid in inc.runs.get("full", []) + inc.runs.get("confirm", []):
        try:
            d = json.loads((runs_dir / rid / "diagnosis.json").read_text())
        except (OSError, json.JSONDecodeError):
            continue
        lab = next((x for x in d["labels"] if x["name"] == "data_limited"), None)
        if lab and (best is None or lab["confidence"] > best["confidence"]):
            best = lab
    return best


def _spawn(args: list[str], log_name: str) -> int:
    logf = open(STATE / log_name, "a")
    proc = subprocess.Popen([sys.executable, "-m", "autolab.cli", *args], cwd=REPO_ROOT, stdout=logf,
                            stderr=subprocess.STDOUT, start_new_session=True)
    return proc.pid


def _alive(pid: int | None) -> bool:
    if not pid:
        return False
    try:
        os.kill(pid, 0)
    except OSError:
        return False
    try:  # reap if it's our finished child
        return os.waitpid(pid, os.WNOHANG) == (0, 0)
    except ChildProcessError:
        return True


def data_step(ctl: dict, session: dict, progs: dict, calls: dict, cfg: dict, paths: ev.Paths, log) -> None:
    from autolab.config import load_config

    flow = ctl.setdefault("data_flow", {})
    sname = session.get("name")
    if flow.get("session") != sname:
        flow.clear()
        flow.update(session=sname, state="idle")
    datasets_dir = load_config().datasets_dir
    runs_dir = RUNS

    if flow["state"] in ("idle", "uploading", "checking") and not budget_ok(flow, session, calls, cfg):
        return  # the data check trains 3 full seeds; wait for the rolling-24h budget like proposals do
    if flow["state"] == "idle":
        lab = incumbent_diagnosis(session, progs, runs_dir)
        if not lab or lab["confidence"] < cfg.get("data_trigger_confidence", 0.75):
            return
        if any(c.get("program") == session["incumbent"] and c.get("kind", "data") == "data"
               for c in session.get("data_checks", [])):
            return
        cur = session.get("dataset_id") or ev.evolve_cfg()["dataset_id"]
        cur_docs = json.loads((datasets_dir / cur / "dataset.json").read_text())["docs"] \
            if (datasets_dir / cur / "dataset.json").exists() else int(re.sub(r"\D", "", cur)) * 1000
        want = int(cur_docs * cfg.get("data_growth", 2))
        from autolab.datasets import dataset_id

        target = dataset_id(want)
        flow.update(target=target, trigger=lab, started=iso(now()))
        note("data_limited", session=sname, program=session["incumbent"], confidence=lab["confidence"],
             evidence=lab["evidence"], plan=f"build {target} ({want:,} docs) and test the incumbent on it")
        if (datasets_dir / target / "train.pt").exists():
            flow["state"] = "built"
        else:
            bigger = sorted((d for d in datasets_dir.iterdir() if (d / "dataset.json").exists()
                             and json.loads((d / "dataset.json").read_text())["docs"] > want), key=lambda d: d.name)
            args = (["data", "slice", bigger[0].name, "--docs", str(want)] if bigger
                    else ["data", "build", "--num-examples", str(want)])
            flow.update(state="building", pid=_spawn(args, "data_build.log"), cmd=" ".join(args))
            log(f"data: {' '.join(args)} (pid {flow['pid']})")
    elif flow["state"] == "building":
        if _alive(flow.get("pid")):
            return
        if (datasets_dir / flow["target"] / "dataset.json").exists():
            flow["state"] = "built"
        else:
            flow["state"] = "failed"
            note("data_build_failed", session=sname, target=flow["target"], log="autolab/state/data_build.log")
    if flow["state"] == "built":
        flow.update(state="uploading", pid=_spawn(["modal", "upload-data"], "data_upload.log"))
    elif flow["state"] == "uploading":
        if _alive(flow.get("pid")):
            return
        chk = ev.start_data_check(session["incumbent"], flow["target"], paths=paths)
        flow.update(state="checking", check=chk["id"])
        note("data_check_started", session=sname, dataset=flow["target"], program=session["incumbent"], runs=chk["runs"])
    elif flow["state"] == "checking":
        chk = next((c for c in ev.load_session(paths).get("data_checks", []) if c["id"] == flow["check"]), None)
        if not chk or chk["status"] == "running":
            return
        note("data_check_done", session=sname, dataset=flow["target"], verdict=chk.get("verdict"),
             helped=chk.get("helped"), losses=chk.get("losses"))
        if not chk.get("helped"):
            flow["state"] = "not_helped"
            return
        submit_screens(flow, session, progs, paths, log)
    elif flow["state"] == "baselining":
        if any(calls.get(r, {}).get("state", "pending") == "pending" for r in flow["screen_runs"]):
            return
        new = switch_session(flow, session, progs, paths, log)
        flow["state"] = "switched"
        flow["new_session"] = new


def budget_ok(flow: dict, session: dict, calls: dict, cfg: dict) -> bool:
    """Room in the rolling-24h budget for what the next data step will submit."""
    from autolab import modal_backend as mb

    if flow["state"] not in ("idle", "uploading"):
        return True  # nothing new gets submitted before the verdict
    llm = []
    try:
        llm = [json.loads(x) for x in (STATE / "llm_spend.jsonl").read_text().splitlines() if x.strip()]
    except OSError:
        pass
    cost = 3 * (session["wall_caps"]["full"] + 180) * mb.price_per_s(ev.evolve_cfg()["gpu"])
    ok = spend_24h(calls, llm, now())["total"] + cost <= daily_budget(load_control(), cfg)
    flow["waiting_for_budget"] = not ok
    return ok


def submit_screens(flow: dict, session: dict, progs: dict, paths: ev.Paths, log, submit=None) -> None:
    from autolab.config import load_config
    from autolab.program import base_sources, materialize, render

    if submit is None:
        from autolab.modal_backend import submit as modal_submit

        def submit(req, gpu, src):
            return modal_submit(req, gpu, src_root=src)

    cfg = ev.evolve_cfg()
    p = progs[session["incumbent"]]
    src = materialize(render(base_sources(REPO_ROOT, p.base_commit), p.blocks), paths.work(f"data-screen-{p.id}"))
    ids = []
    for seed in (1, 2, 3):
        req = ev._request(p, "screen", seed, cfg, session)
        dataset = flow.get("dataset", flow["target"])
        req.run_id = f"ev-{session.get('name')}-{flow.get('kind', 'data')}-{flow['target']}-{p.id}-screen-s{seed}"
        req.dataset_id = dataset
        req.train_tokens = str(load_config().datasets_dir / dataset / "train.pt")
        submit(req, cfg["gpu"], src)
        ids.append(req.run_id)
    flow.update(state="baselining", screen_runs=ids)
    log(f"{flow.get('kind', 'data')}: {flow['target']} helped; baselining screens {ids}")


def switch_session(flow: dict, session: dict, progs: dict, paths: ev.Paths, log) -> str:
    """Start a new session on the bigger data with the incumbent as its p0."""
    chk = next(c for c in session["data_checks"] if c["id"] == flow["check"])
    inc = progs[session["incumbent"]]
    name = f"{session.get('name', 's').split('-')[0]}+{flow['target']}"
    new_paths = ev.Paths(ev.STATE_ROOT / name)
    ev.init_session(session["base_commit"], inc.hparams, {"screen": flow["screen_runs"], "full": chk["runs"]},
                    paths=new_paths, budgets=session["budgets"], name=name, blocks=inc.blocks,
                    dataset_id=flow["target"], rationale=f"{inc.id} of {session.get('name')} moved to {flow['target']}")
    ev.set_active_session(name)
    note("session_switched", old=session.get("name"), new=name, dataset=flow["target"], verdict=chk["verdict"])
    log(f"switched to session {name} on {flow['target']}")
    return name


def port_from_old_sessions(ctl: dict, session: dict, log) -> list[str]:
    """Programs accepted in other sessions (e.g. after a data switch) get re-evaluated here, once."""
    ported = ctl.setdefault("ported", [])
    out = []
    for paths in ev.all_session_paths():
        other = ev.load_session(paths)
        if not other or other.get("name") == session.get("name"):
            continue
        for p in ev.programs(paths).values():
            key = f"{other.get('name')}/{p.id}"
            if p.parent_id is None or p.status != "accepted" or key in ported:
                continue
            child = ev.port(p, other.get("name"))
            ported.append(key)
            note("ported", session=session.get("name"), program=child.id, source=key,
                 full_mean_there=p.scores.get("full_mean"))
            log(f"ported {key} -> {session.get('name')}/{child.id}")
            out.append(child.id)
    return out


# --- the compute ladder -----------------------------------------------------------------------------


def stalled_children(session: dict, progs: dict) -> int:
    """Finished children since the incumbent was set that didn't beat it (the search has stalled)."""
    since = (session.get("incumbent_history") or [{}])[-1].get("at", "")
    return sum(1 for p in progs.values() if p.parent_id and p.status in ev.DONE and p.status != "accepted"
               and p.created_at >= since)


def ladder_step(ctl: dict, session: dict, progs: dict, calls: dict, cfg: dict, paths: ev.Paths, log) -> None:
    """Raise the token budget when searching at this one has stalled and training longer clearly pays.

    idle -> (stalled >= ladder_patience, next budget <= max_full_tokens, data policy quiet, budget ok)
    checking (incumbent at factor x tokens, 3 seeds) -> not_helped | baselining (3 screens) -> switched
    (new session "<name>@<N>M" with that budget; the data policy re-arms there).
    """
    if not cfg.get("ladder", True):
        return
    flow = ctl.setdefault("ladder", {})
    sname = session.get("name")
    if flow.get("session") != sname:
        flow.clear()
        flow.update(session=sname, state="idle")
    cur = session["budgets"]["full_tokens"]
    step_tokens = ev.evolve_cfg()["block_size"] * progs[session["incumbent"]].hparams["batch_size"]
    nxt = int(round(cur * cfg.get("ladder_factor", 1.5) / step_tokens)) * step_tokens
    if flow["state"] == "idle":
        data_busy = ctl.get("data_flow", {}).get("state") not in (None, "idle", "not_helped", "failed")
        stalled = stalled_children(session, progs)
        if (data_busy or nxt > cfg.get("max_full_tokens", cur) or stalled < cfg.get("ladder_patience", 4)
                or any(c.get("kind") == "budget" and c["program"] == session["incumbent"]
                       for c in session.get("data_checks", []))):
            flow["waiting"] = {"stalled": stalled, "next_tokens": nxt, "data_busy": data_busy}
            return
        from autolab.modal_backend import price_per_s

        cost = 3 * (session["wall_caps"]["full"] * nxt / cur + 180) * price_per_s(ev.evolve_cfg()["gpu"])
        if spend_24h(calls, _llm_spend(), now())["total"] + cost > daily_budget(ctl, cfg):
            flow["waiting"] = {"budget": f"needs ~${cost:.2f}"}
            return
        dataset = session.get("dataset_id") or ev.evolve_cfg()["dataset_id"]
        chk = ev.start_data_check(session["incumbent"], dataset, paths=paths, tokens=nxt)
        flow.update(state="checking", check=chk["id"], kind="budget", target=f"{nxt // 1_000_000}M", dataset=dataset,
                    tokens=nxt, started=iso(now()))
        flow.pop("waiting", None)
        note("ladder_check_started", session=sname, program=session["incumbent"], tokens=nxt, stalled=stalled,
             runs=chk["runs"])
        log(f"ladder: {stalled} children stalled; testing {session['incumbent']} at {nxt:,} tokens")
    elif flow["state"] == "checking":
        chk = next((c for c in ev.load_session(paths).get("data_checks", []) if c["id"] == flow["check"]), None)
        if not chk or chk["status"] == "running":
            return
        note("ladder_check_done", session=sname, tokens=flow["tokens"], verdict=chk.get("verdict"),
             helped=chk.get("helped"), losses=chk.get("losses"))
        if not chk.get("helped"):
            flow["state"] = "not_helped"
            return
        submit_screens(flow, session, progs, paths, log)
    elif flow["state"] == "baselining":
        if any(calls.get(r, {}).get("state", "pending") == "pending" for r in flow["screen_runs"]):
            return
        chk = next(c for c in session["data_checks"] if c["id"] == flow["check"])
        inc = progs[session["incumbent"]]
        name = f"{sname.split('@')[0]}@{flow['target']}"
        ev.init_session(session["base_commit"], inc.hparams, {"screen": flow["screen_runs"], "full": chk["runs"]},
                        paths=ev.Paths(ev.STATE_ROOT / name),
                        budgets={**session["budgets"], "full_tokens": flow["tokens"]}, name=name, blocks=inc.blocks,
                        dataset_id=flow["dataset"],
                        rationale=f"{inc.id} of {sname} at {flow['tokens']:,} tokens (compute ladder)")
        ev.set_active_session(name)
        note("session_switched", old=sname, new=name, tokens=flow["tokens"], verdict=chk["verdict"])
        log(f"ladder: switched to session {name}")
        flow.update(state="switched", new_session=name)


def _llm_spend() -> list[dict]:
    try:
        return [json.loads(x) for x in (STATE / "llm_spend.jsonl").read_text().splitlines() if x.strip()]
    except OSError:
        return []


# --- one controller step ------------------------------------------------------------------------------


def step(log=print, generate=None, t: datetime | None = None) -> dict:
    """Run once per daemon cycle. Returns a small status dict for the heartbeat."""
    from autolab import modal_backend as mb
    from autolab.llm import RateLimited

    t = t or now()
    ctl = load_control()
    status = {"enabled": ctl.get("enabled", False)}
    session_paths = ev.Paths()
    session = ev.load_session(session_paths)
    if session is None:
        return {**status, "note": "no session"}
    progs = ev.programs(session_paths)
    ccfg = controller_cfg()

    # record newly finished programs (and commit acceptances) in every session, whether or not
    # proposing is enabled: an older session can still finish programs after a data switch
    from autolab.program import save

    for spaths in ev.all_session_paths():
        sess = ev.load_session(spaths)
        if not sess:
            continue
        name = sess.get("name")
        seen = set(ctl.setdefault("recorded", {}).get(name, []))
        for p in ev.programs(spaths).values():
            if p.parent_id is None or p.id in seen or p.status not in ev.DONE:
                continue
            note("program_done", session=name, program=p.id, status=p.status, stage=p.stage,
                 reason=p.reason[:300], full_mean=p.scores.get("full_mean"), n_seeds=p.scores.get("n_seeds"),
                 created_by=p.created_by)
            if p.status == "accepted" and ccfg.get("commit_accepted", True):
                p.meta["commit"] = commit_accepted(p, sess, log=log)
                save(p, spaths.programs)
            seen.add(p.id)
        ctl["recorded"][name] = sorted(seen)
    progs = ev.programs(session_paths)

    if not ctl.get("enabled"):
        save_control(ctl)
        return status

    calls = mb.load_calls()
    try:  # the data policy spends money too, so it only runs while enabled
        data_step(ctl, session, progs, calls, ccfg, session_paths, log)
    except Exception as exc:  # noqa: BLE001 - never let the data policy take the loop down
        log(f"data policy error: {type(exc).__name__}: {exc}")
        ctl.setdefault("data_flow", {})["error"] = str(exc)[:500]
    if ctl.get("data_flow", {}).get("state") == "switched":  # new session: reload
        session_paths = ev.Paths()
        session, progs = ev.load_session(session_paths), ev.programs(ev.Paths())
    try:
        ladder_step(ctl, session, progs, calls, ccfg, session_paths, log)
    except Exception as exc:  # noqa: BLE001
        log(f"ladder error: {type(exc).__name__}: {exc}")
        ctl.setdefault("ladder", {})["error"] = str(exc)[:500]
    if ctl.get("ladder", {}).get("state") == "switched":
        session_paths = ev.Paths()
        session, progs = ev.load_session(session_paths), ev.programs(ev.Paths())
    port_from_old_sessions(ctl, session, log)
    status["data"] = {k: v for k, v in ctl.get("data_flow", {}).items() if k in ("state", "target", "check", "new_session")}
    status["ladder"] = {k: v for k, v in ctl.get("ladder", {}).items() if k in ("state", "target", "waiting", "new_session")}
    paused = ctl.get("paused_until")
    if paused and datetime.fromisoformat(paused) > t:
        save_control(ctl)
        return {**status, "paused_until": paused, "pause_reason": ctl.get("pause_reason")}

    children = [p for p in progs.values() if p.parent_id is not None]
    recent = sorted(children, key=lambda p: int(p.id[1:]))[-ccfg.get("max_consecutive_early_rejects", 4):]
    if (len(recent) == ccfg.get("max_consecutive_early_rejects", 4)
            and all(p.status == "rejected" and p.stage in EARLY for p in recent)
            and ctl.get("early_reject_ack") != recent[-1].id):
        ctl.update(paused_until=iso(t + timedelta(hours=6)), early_reject_ack=recent[-1].id,
                   pause_reason=f"{len(recent)} proposals in a row rejected before training ({recent[-1].reason[:160]})")
        note("paused", reason=ctl["pause_reason"], until=ctl["paused_until"])
        save_control(ctl)
        return {**status, "paused_until": ctl["paused_until"]}

    in_flight = sum(p.status not in ev.DONE for p in children)
    if len(children) >= ccfg.get("max_programs_per_session", 200):
        save_control(ctl)
        return {**status, "note": "max_programs_per_session reached"}
    llm_spend = []
    try:
        llm_spend = [json.loads(x) for x in (STATE / "llm_spend.jsonl").read_text().splitlines() if x.strip()]
    except OSError:
        pass
    price = mb.price_per_s(ev.evolve_cfg()["gpu"])
    made = 0
    while in_flight < ccfg.get("max_in_flight", 4):
        sp = spend_24h(mb.load_calls(), llm_spend, t)
        need = expected_candidate_usd(session, price, ccfg)
        modal_total = sum(c.get("usd") or c.get("usd_estimate") or 0 for c in mb.load_calls().values())
        daily = daily_budget(ctl, ccfg, t)
        if sp["total"] + need > daily:
            status["budget"] = f"24h spend ${sp['total']:.2f} + next ~${need:.2f} > ${daily}"
            break
        if modal_total + need > mb._CFG.get("max_usd", 25.0):
            status["budget"] = f"Modal total ${modal_total:.2f} + ~${need:.2f} > cap ${mb._CFG.get('max_usd')}"
            break
        try:
            child = (generate or _generate)(log)
        except RateLimited as exc:
            until = parse_reset(str(exc), t)
            ctl.update(paused_until=iso(until), pause_reason=f"Claude usage limit: {str(exc)[:200]}")
            note("paused", reason=ctl["pause_reason"], until=ctl["paused_until"])
            break
        note("proposed", session=session.get("name"), program=child.id, parent=child.parent_id,
             created_by=child.created_by, rationale=child.rationale[:400], hparams_patch={
                 k: v for k, v in child.hparams.items() if progs.get(child.parent_id) and
                 progs[child.parent_id].hparams.get(k) != v},
             status=child.status, fallback=child.meta.get("fallback_reason"), cost_usd=child.meta.get("cost_usd"))
        made += 1
        in_flight += child.status not in ev.DONE
    save_control(ctl)
    render_notebook_md(read_notebook(), ev.load_session(ev.Paths()), ev.programs(ev.Paths()))
    return {**status, "proposed": made, "in_flight": in_flight}


def _generate(log):
    from autolab.generate import generate_one

    return generate_one(log=log)
