"""The M6 session report: autolab/SESSION_1.md, regenerated by the daemon (hourly) and on demand.

    uv run autolab session-report

Built only from what the system recorded (sessions, programs, Modal calls, Claude calls, the
notebook), so it reads the same whether or not anyone was watching:
- the path of the best result: sessions, data switches, incumbent history;
- best-so-far after each full-budget evaluation;
- the current best program's lineage, with each step's rationale, change and score;
- the cascade funnel and rejection reasons per session;
- proposer statistics (per model: proposals, how far they got, acceptances, cost);
- spend by stage (baselines, screens, full runs, confirmations, data checks) and GPU-hours;
- observations that follow from the numbers.
"""

from __future__ import annotations

import json
import re
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

from autolab import evaluate as ev
from autolab.config import REPO_ROOT

OUT = REPO_ROOT / "autolab" / "SESSION_1.md"
STAGE_ORDER = ["static", "cpu", "params", "screen", "full", "confirm", "done"]


def _read_jsonl(path: Path) -> list[dict]:
    try:
        return [json.loads(x) for x in path.read_text().splitlines() if x.strip()]
    except (OSError, json.JSONDecodeError):
        return []


def _stage_of_run(run_id: str) -> str:
    if not run_id.startswith("ev-"):
        return "baselines & prep experiments"
    if "-data-" in run_id:
        return "data checks" if "-screen-" not in run_id else "data-switch screens"
    m = re.search(r"-(screen|full|confirm)-s\d+$", run_id)
    return {"screen": "screens", "full": "full runs", "confirm": "confirmations"}.get(m.group(1) if m else "", "other")


def _hp_change(parent: dict, child: dict) -> str:
    ch = [f"{k} {parent.get(k)}→{v}" for k, v in child.items() if parent.get(k) != v]
    return ", ".join(ch) or "no hparam change"


def build(out: Path = OUT) -> str:
    from autolab.modal_backend import load_calls

    sessions = []
    for paths in ev.all_session_paths():
        s = ev.load_session(paths)
        if s and not s.get("ablation"):  # control arms (autolab ablation) are reported by `autolab ablation status`
            sessions.append((paths, s, ev.programs(paths)))
    sessions.sort(key=lambda t: t[1]["created"])
    calls = load_calls()
    llm = _read_jsonl(REPO_ROOT / "autolab" / "state" / "llm_spend.jsonl")
    notebook = _read_jsonl(REPO_ROOT / "autolab" / "notebook.jsonl")
    active = ev.active_session_name()
    L = [f"# Autolab session report", "",
         f"Generated {datetime.now(timezone.utc).isoformat(timespec='minutes')} by `autolab session-report` "
         f"(the daemon refreshes it hourly). Active session: `{active}`.", ""]

    # --- headline --------------------------------------------------------------------------------
    best = None
    for paths, s, progs in sessions:
        inc = progs[s["incumbent"]]
        if inc.scores.get("full_mean") is not None and (best is None or inc.scores["full_mean"] < best[2].scores["full_mean"]):
            best = (paths, s, inc)
    for _, s_, _ in sessions:
        s_.setdefault("dataset_id", None)
        s_["dataset_id"] = s_["dataset_id"] or ev.evolve_cfg()["dataset_id"]  # sessions before data switching
    first = None
    if best:
        # the starting point = p0 of the earliest session at the best's token budget (comparable numbers)
        same = [t for t in sessions if t[1]["budgets"]["full_tokens"] == best[1]["budgets"]["full_tokens"]]
        first_s = same[0][1] if same else sessions[0][1]
        first = (same[0] if same else sessions[0])[2]["p0"]
    if best and first:
        _, bs, bp = best
        L += ["## Headline", "",
              f"- Best: **{bs.get('name')}/{bp.id}**, full val loss **{bp.scores['full_mean']:.4f}** over "
              f"{bp.scores.get('n_seeds')} seeds on `{bs.get('dataset_id')}` at {bs['budgets']['full_tokens']:,} tokens.",
              f"- Start at the same budget: `{first_s.get('name')}` p0 {first.scores['full_mean']:.4f} "
              f"(σ {first_s['noise']['full']['std']:.4f}, `{first_s.get('dataset_id')}`). Owner's best single run for "
              f"reference: 4.7118 (seed 42, data20k).",
              f"- Improvement: **{first.scores['full_mean'] - bp.scores['full_mean']:.4f}** nats "
              f"({(first.scores['full_mean'] - bp.scores['full_mean']) / first_s['noise']['full']['std']:.1f}σ of the "
              f"starting seed noise).", ""]

    # --- path: sessions, data, incumbents -----------------------------------------------------------
    L += ["## How we got here", ""]
    for paths, s, progs in sessions:
        L.append(f"### Session `{s.get('name')}` — data `{s.get('dataset_id')}`, full budget {s['budgets']['full_tokens']:,} "
                 f"tokens, seed noise σ {s['noise']['full']['std']:.4f}")
        L.append("")
        for h in s.get("incumbent_history", []):
            p = progs.get(h["program"])
            L.append(f"- {h['at'][:16]} incumbent **{h['program']}** {h['full_mean']:.4f}"
                     + (f" — {' '.join(p.rationale.split())[:160]}" if p and p.parent_id else ""))
        for c in s.get("data_checks", []):
            L.append(f"- data check `{c['dataset']}` on {c['program']}: {c.get('verdict', c['status'])}")
        L.append("")

    # --- best-so-far vs evaluations -----------------------------------------------------------------
    budget = best[1]["budgets"]["full_tokens"] if best else None
    L += [f"## Best so far after each full-budget evaluation ({budget:,} tokens)" if budget else "## Best so far", "",
          "| # | when | session/program | full val (1st seed) | best so far |", "| --- | --- | --- | --- | --- |"]
    evals = []
    for paths, s, progs in sessions:
        if budget and s["budgets"]["full_tokens"] != budget:
            continue
        for p in progs.values():
            for st in p.stages:
                if st["stage"] == "full" and st.get("ok") and st.get("loss") is not None:
                    evals.append((st["at"], f"{s.get('name')}/{p.id}", st["loss"], s.get("dataset_id")))
    best_so_far = None
    for i, (at, who, loss, ds) in enumerate(sorted(evals), 1):
        best_so_far = loss if best_so_far is None else min(best_so_far, loss)
        L.append(f"| {i} | {at[:16]} | {who} ({ds}) | {loss:.4f} | {best_so_far:.4f} |")
    L.append("")

    # --- lineage ---------------------------------------------------------------------------------------
    if best:
        L += ["## Lineage of the best program", ""]
        paths, s, p = best
        chain = []
        while p is not None:
            chain.append((s, p))
            src = p.meta.get("ported_from")
            if src:
                sname, pid = src.split("/")
                sp = next(((pp, ss, pr) for pp, ss, pr in sessions if ss.get("name") == sname), None)
                s, p = (sp[1], sp[2][pid]) if sp else (s, None)
            else:
                p = ev.programs(ev.Paths(ev.STATE_ROOT / s["name"])).get(p.parent_id) if p.parent_id else None
        for s_, p_ in reversed(chain):
            parent = ev.programs(ev.Paths(ev.STATE_ROOT / s_["name"])).get(p_.parent_id) if p_.parent_id else None
            code = [key.split(":")[1] for key in p_.blocks if parent and parent.blocks.get(key) != p_.blocks[key]]
            L.append(f"- **{s_.get('name')}/{p_.id}** ({p_.created_by}) — "
                     f"{p_.scores.get('full_mean', float('nan')):.4f} over {p_.scores.get('n_seeds', 0)} seeds; "
                     f"{_hp_change(parent.hparams, p_.hparams) if parent else 'initial'}"
                     f"{'; code: ' + ', '.join(code) if code else ''}")
            if p_.parent_id:
                L.append(f"  - {' '.join(p_.rationale.split())[:400]}")
        L.append("")

    # --- funnel & failure modes ----------------------------------------------------------------------
    L += ["## Cascade funnel and rejections", ""]
    for paths, s, progs in sessions:
        kids = [p for p in progs.values() if p.parent_id]
        if not kids:
            continue
        status = Counter(p.status for p in kids)
        where = Counter(p.stage for p in kids if p.status == "rejected")
        L.append(f"- `{s.get('name')}`: {len(kids)} children — " + ", ".join(f"{k} {v}" for k, v in status.most_common())
                 + (" · rejected at " + ", ".join(f"{k} {v}" for k, v in where.most_common()) if where else ""))
        for p in kids:
            if p.status == "rejected":
                L.append(f"  - {p.id} ({p.created_by}) @ {p.stage}: {p.reason[:200]}")
    L.append("")

    # --- proposer --------------------------------------------------------------------------------------
    L += ["## Proposer (Claude) statistics", ""]
    per = defaultdict(Counter)
    for paths, s, progs in sessions:
        for p in progs.values():
            if not p.parent_id:
                continue
            who = p.created_by if not p.created_by.startswith("port:") else "port"
            per[who]["proposed"] += 1
            per[who][p.status] += 1
            if p.status != "rejected" or p.stage in ("screen", "full", "confirm"):
                per[who]["trained"] += 1
    L += ["| proposer | proposed | trained | accepted | contender | evaluated | rejected |", "| --- | --- | --- | --- | --- | --- | --- |"]
    for who, c in sorted(per.items()):
        L.append(f"| {who} | {c['proposed']} | {c['trained']} | {c['accepted']} | {c['contender']} | {c['evaluated']} | {c['rejected']} |")
    fails = Counter((e.get("error") or "")[:60] for e in llm if not e.get("ok"))
    L += ["", f"- Claude calls: {len(llm)} ({sum(e.get('ok', False) for e in llm)} ok), "
              f"${sum(e.get('usd') or 0 for e in llm):.2f}. Failures: "
              + (", ".join(f"{k or 'unknown'} ×{v}" for k, v in fails.items()) or "none") + ".",
          f"- Fallback mutations (proposer failed): "
          f"{sum(1 for _, _, pr in sessions for p in pr.values() if p.created_by == 'mutation')}.", ""]

    # --- spend -------------------------------------------------------------------------------------------
    by = defaultdict(lambda: [0.0, 0.0, 0])
    for rid, c in calls.items():
        k = _stage_of_run(rid)
        by[k][0] += c.get("usd") or 0
        by[k][2] += 1
        try:
            by[k][1] += json.loads((REPO_ROOT / "autolab" / "runs" / rid / "launch.json").read_text()).get("wall_s") or 0
        except (OSError, json.JSONDecodeError):
            pass
    L += ["## Spend", "", "| stage | runs | GPU-hours | $ |", "| --- | --- | --- | --- |"]
    for k, (usd, wall, n) in sorted(by.items(), key=lambda kv: -kv[1][0]):
        L.append(f"| {k} | {n} | {wall / 3600:.2f} | {usd:.2f} |")
    total = sum(v[0] for v in by.values())
    L += [f"| **Modal total** | {sum(v[2] for v in by.values())} | {sum(v[1] for v in by.values()) / 3600:.2f} | **{total:.2f}** |",
          f"| Claude | {len(llm)} calls | | {sum(e.get('usd') or 0 for e in llm):.2f} |", "",
          "Modal $ = wall time × GPU list price (L4); CPU/memory charges excluded, so a lower bound.", ""]

    # --- notebook tail -----------------------------------------------------------------------------------
    pauses = [e for e in notebook if e["event"] == "paused"]
    if pauses:
        L += ["## Pauses", ""] + [f"- {e['at'][:16]}: {e.get('reason', '')[:200]} (until {e.get('until', '')[:16]})" for e in pauses[-5:]] + [""]
    text = "\n".join(L) + "\n"
    out.write_text(text)
    return text
